baseurl = "https://apilchaudhary.com.np"
title = "Apil Chaudhary"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "apil"

[markup.highlight]
style = "monokai"

[params]
  author = "Apil Chaudhary"
  info = "Robotics & AI | Cloud Computing"
  description = "Apil Chaudhary's personal website"
  keywords = "blog,developer,personal"
  # avatarurl = "images/avatar.webp"
  #gravatar = "apil.chaudhary1@gmail.com"

  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  katex = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tyro-apil/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/apil-chaudhary/"

# Menu links
[[menu.main]]
  name = "Notes"
  weight = 1
  url  = "notes/"
[[menu.main]]
  name = "Tutorials"
  weight = 2
  url = "tutorials/"
[[menu.main]]
  name = "About"
  weight = 6
  url = "about/"

[caches]
  [caches.images]
    dir = ":cacheDir/images"